name: test

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        st-version: [3, 4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@master
        with:
          sublime-text-version: ${{ matrix.st-version }}
          unittesting-version: master
          # we need turbovnc to capture on_activated call in ubuntu
          display: turbovnc
          # we need xfce for the subl command to work in st3
          window-manager: xfce
      - uses: SublimeText/UnitTesting/actions/run-tests@master
        with:
          coverage: true
          codecov-upload: true
